[project]
name = "workoutapp"
version = "0.1.0"
description = "Workout personal app"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "textual>=7.0.1",
    "ty>=0.0.10",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]
